import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Box, Grid, Paper, Stack, Typography, Container } from "@mui/material";
import Colors from '@/common/Colorscomponents';
import AIRAMonoLinesLeft from '@/components/AIRAMonoLinesLeft/AIRAMonoLinesLeftcomponents';
import RoundedButton from '@/components/RoundedButton/RoundedButtoncomponents';
import macBookImage from '../../public/images/home/macbook.svg'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next';
import styles from '../styles/Home.module.css'
import RefereceStack from '@/components/ReferenceStack/RefereceStackcomponents';
import PowerOfIntelligence from '@/components/PowerOfIntelligence/PowerOfIntelligencecomponents';
import Offering from '@/components/Offering/Offeringcomponents';
import ConnectToSystem from '@/components/ConnectToSystem/ConnectToSystemcomponents';
import DiscoverStack from '../components/DiscoverStack/DiscoverStack';
import TryAiraDialog from '@/components/TryAiraDialog/TryAiraDialogcomponents';
import { useRouter } from 'next/router';

const EBONYHEIGHT = "600";

function Home() {
  const [lang, setLang] = useState('en');
  useEffect(() => {
    setLang(localStorage?.getItem('lang'));
  }, []);

  const { t } = useTranslation('common')
  const [openTryAIRADialog, setOpenTryAIRADialog] = useState(false);

  const router = useRouter();

  return (
    <>
      <Head>
        <title>AIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="icon" type="image/svg+xml" href="/monogram.svg" />
      </Head>

      <Box sx={{ pt: { xs: 8.5, md: 0 } }}>
        <Paper sx={{ position: "relative" }} elevation={0}>
          <Grid
            container
            justifyContent="center"
            alignItems="center"
            flexDirection={{ xs: "column-reverse", md: "row" }}
          >
            <Grid item xs={12} md={6}>
              <Container>
                <Box
                  sx={{
                    width: '100%',
                    display: 'flex',
                    justifyContent: 'flex-end',
                    alignItems: 'flex-end',
                    flexDirection: 'column'
                  }}
                >
                  <Box sx={{ width: { xs: '100%', md: '60%' }, pt: { xs: 5, md: 0 } }}>
                    <Typography variant="h4" sx={{ fontWeight: 800 }}>
                      {/* Revolutionize Your Productivity With{" "} */}
                      {console.log(lang)}
                      {lang === 'fr' ? `Hyper-automatisation de nouvelle génération` : lang === 'sp' ? 'Hiperautomatización de próxima' : lang === 'ar' ? 'الأتمتة الفائقة للمؤسسات' : lang === 'gr' ? 'Hyperautomatisierung der nächsten' : 'Next-Gen Hyper-automation for'} {" "}
                      <span style={{ color: Colors.airaSecondary }}>
                        {/* AI Automation */}
                        {lang === 'fr' ? `pour les entreprises` : lang === 'sp' ? 'generación para empresas' : lang === 'ar' ? 'لجيل التالي من|' : lang === 'gr' ? 'Generation für Unternehmen' : 'Enterprises'}
                      </span>
                    </Typography>

                    <Typography variant="body1" sx={{ mt: 3 }}>
                      <span style={{ fontWeight: 700 }}>
                        {/* Artificially Intelligent Robotic Automation, */}
                        {lang === 'fr' ? `Solution d'hyper-automatisation de pointe, combinant de manière transparente l'automatisation des processus robotiques (RPA) et l'intelligence artificielle (IA) pour évolutionner le mode de fonctionnement des entreprises.` : lang === 'sp' ? 'Solución de hiperautomatización de vanguardia que combina a la perfección la automatización de procesos robóticos (RPA) y la inteligencia artificial (IA) para revolucionar la forma en que operan las empresas.' : lang === 'ar' ? 'حل متطور للأتمتة الفائقة، يمزج بسلاسة بين أتمتة العمليات الروبوتية (RPA) والذكاء الاصطناعي (AI) لإحداث ثورة في طريقة عمل الشركات.حل متطور للأتمتة الفائقة، يمزج بسلاسة بين أتمتة العمليات الروبوتية (RPA) والذكاء الاصطناعي (AI)' : lang === 'gr' ? 'Modernste Hyperautomatisierungslösung, die robotergestützte Prozessautomatisierung (RPA) und künstliche Intelligenz (KI) nahtlos miteinander verbindet, um die Arbeitsweise von ' : 'Cutting-Edge Hyper-Automation Solution, Seamlessly Blending Robotic Process Automation (RPA) and Artificial Intelligence (AI) To Revolutionise The Way Businesses Operate'}
                      </span>{" "}
                      {/* Say goodbye to manual tasks and hello to a more efficient and
                      profitable enterprise. */}
                      {/* {lang === 'fr' ? `évolutionner le mode de fonctionnement des entreprises.` : lang === 'sp' ? 'la forma en que operan las empresas.' : lang === 'ar' ? 'حل متطور للأتمتة الفائقة، يمزج بسلاسة بين أتمتة العمليات الروبوتية (RPA) والذكاء الاصطناعي (AI)' : lang === 'gr' ? 'Unternehmen zu revolutionieren.' : 'To Revolutionise The Way Businesses Operate.'} */}
                    </Typography>
                    <RoundedButton onClick={() => {
                      setOpenTryAIRADialog(true);
                    }} label={lang === 'fr' ? `Réservez une démo Bouton d'appel à l'action` : lang === 'sp' ? 'Reserve una demostración Botón de llamada a la acción' : lang === 'ar' ? 'حجز زر تجريبي للحث على اتخاذ إجراء' : lang === 'gr' ? 'Buchen Sie eine Demo-Call-to-Action-Schaltfläche' : 'Book a Demo'} sx={{ mt: 3 }} />
                  </Box>
                </Box>
              </Container>
            </Grid>
            <Grid className='uu' item xs={12} md={6}>
              <Box

                sx={{
                  width: "100%",
                  backgroundImage: "url(/images/home/ebony.png)",
                  backgroundRepeat: "no-repeat",
                  backgroundPosition: "right top",
                  backgroundSize: 'cover',
                  height: '55vw',
                  display: 'flex',
                  justifyContent: 'start',
                  alignItems: 'center',
                }}

              >
                <Box sx={{ py: 5 }}>
                  <Image

                    src={macBookImage}
                    width={0}
                    height={0}
                    alt='AIRA'
                    sizes="100vw"
                    // style={{ width: '100%', height: 'auto' }}
                    className={styles.macbookImage}
                  />
                </Box>
              </Box>
            </Grid>
          </Grid>

          <Container maxWidth="lg">
            <Grid
              sx={{ pt: 4 }}
              container
              spacing={5}
              justifyContent="left"
              alignItems="center"
            >
              <Grid item xs={12} md={6}>
                <div style={{ position: "relative" }}>
                  <div
                    className='tr1'
                    style={{
                      height: "140px",
                      width: "40px",
                      position: "absolute",
                      transform: "rotate(35deg)",
                      borderRadius: "50px",
                      backgroundColor: Colors.airaPrimary,
                      top: 150,
                      marginLeft: "-30px",
                    }}
                  ></div>
                  <div
                    className='tr11'
                    style={{
                      height: "140px",
                      width: "40px",
                      top: 200,
                      transform: "rotate(35deg)",
                      position: "absolute",
                      borderRadius: "50px",
                      backgroundColor: Colors.airaSecondary,
                    }}
                  ></div>
                  <div
                    className='tr111'
                    style={{
                      height: "140px",
                      width: "40px",
                      transform: "rotate(35deg)",
                      top: 250,
                      position: "absolute",
                      borderRadius: "50px",
                      marginLeft: "35px",
                      border: `1px solid ${Colors.airaPrimary}`,
                    }}
                  ></div>
                  <Image
                    src="/images/home/learnmore.png"
                    alt="bankingheader"
                    width={0}
                    height={0}
                    sizes="100vw"
                    style={{ width: '100%', height: 'auto', zIndex: 2 }}
                  />
                </div>
              </Grid>
              <Grid item xs={12} md={6}>
                <Stack direction="column" sx={{ py: 2 }}>
                  <Typography variant="h5" sx={{ fontsize: "20 px", fontWeight: 700 }}>
                    <span style={{ color: Colors.airaSecondary }}>
                      {lang === 'fr' ? `Améliorez l'efficacité,` : lang === 'sp' ? 'Aumente la eficiencia,' : lang === 'ar' ? 'وإطلاق العنان للرشاقة' : lang === 'gr' ? 'Steigern Sie die Effizienz,' : 'Elevate Efficiency,'}
                    </span>{" "}
                    {/* Artificially Intelligent Robotic Automation */}
                    {lang === 'fr' ? `libérez l'agilité` : lang === 'sp' ? 'libere la agilidad' : lang === 'ar' ? 'رفع الكفاءة،' : lang === 'gr' ? 'entfesseln Sie Agilität' : 'Unleash Agility'}
                  </Typography>
                  <Typography variant="body1" sx={{ mt: 2, fontWeight: 400 }}>
                    {/* Automated Bots for your Digital Transformation */}
                    {lang === 'fr' ? `Découvrez le pouvoir transformateur d'AIRA, une solution d'hyper-automatisation avancée conçue pour rationaliser et améliorer les processus de base de l'entreprise. Plongez dans le futur de l'automatisation avec les technologies de pointe d'AIRA, permettant aux entreprises d'atteindre une efficacité et une agilité sans précédent.` : lang === 'sp' ? 'Descubra el poder transformador de AIRA, una solución avanzada de hiperautomatización diseñada para optimizar y mejorar los procesos empresariales centrales. Sumérgete en el futuro de la automatización con las tecnologías de vanguardia de AIRA, que permiten a las empresas lograr una eficiencia y agilidad sin precedentes.' : lang === 'ar' ? 'اكتشف القوة التحويلية لـ AIRA، ومستقبل الأتمتة باستخدام تقنيات AIRA المتطورة، وتمكين الشركات من تحقيق كفاءة وسرعة غير مسبوقة.هو حل متقدم للأتمتة الفائقة مصمم لتبسيط العمليات المؤسسية الأساسية وتحسينها. انغمس في' : lang === 'gr' ? 'Entdecken Sie die transformative Kraft von AIRA, einer fortschrittlichen Hyperautomatisierungslösung zur Rationalisierung und Verbesserung zentraler Unternehmensprozesse. Tauchen Sie mit den Spitzentechnologien vonAIRA in die Zukunft der Automatisierung ein und ermöglichen Sie Unternehmen, beispiellose Effizienz und Agilität zu erreichen.' : 'Discover the transformative power of AIRA, an advanced hyper-automation solution designed to streamline and enhance core enterprise processes. Dive into the future of automation with AIRA cutting-edge technologies, empowering businesses to achieve unprecedented efficiency and agility.'}
                  </Typography>
                  {/* <Typography variant="body1" sx={{ mt: 2, lineHeight: 2 }}> */}
                    {/* Introducing AIRA, an AI and ML-powered digital agent that automates
                    your everyday tasks and business processes through robotic
                    automation. It integrates with digital technologies and legacy
                    systems, freeing your workforce from low-output tasks. With AIRA,
                    you can create personalised low-code/no-code automated workflows. */}
                    {/* {lang === 'fr' ? `` : lang === 'sp' ? '' : lang === 'ar' ? '' : lang === 'gr' ? '' : ''}
                  </Typography> */}
                  <div onClick={() => {
                    router.push('/contact');
                  }}>
                    <RoundedButton label="Learn more" sx={{ mt: 3 }} />
                  </div>
                </Stack>
              </Grid>
            </Grid>
          </Container>

          <Container maxWidth="lg">
            <DiscoverStack />
            <Box sx={{ display: "flex", justifyContent: "center", alignSelf: "center", pt: 3 }}>
              <RoundedButton onClick={() => {
                setOpenTryAIRADialog(true);
              }} label={lang === 'fr' ? `Essayez le bouton d'appel à l'action AIRA` : lang === 'sp' ? 'Pruebe el botón de llamada a la acción de AIRA' : lang === 'ar' ? 'جرب زر AIRA Call to Action' : lang === 'gr' ? 'Probieren Sie den Call-to-Action-Button von AIRA aus' : 'Try AIRA'} sx={{ px: 5 }} />
            </Box>
            <Box sx={{ py: 6 }}>
              <RefereceStack />
            </Box>
            <Box>
              <PowerOfIntelligence />
            </Box>
            <Box>
              <Offering />
            </Box>
            <Box>
              <ConnectToSystem />
            </Box>
          </Container>

          {/* <div
            style={{
              position: "absolute",
              right: 0,
              top: 0,
            }}
          >
            <Image
              src="/images/home/ebony.png"
              alt="contact us"
              width="500"
              sizes="100vw"
              height={EBONYHEIGHT}
              style={{
                zIndex: 1,
                // marginRight: "10px",
                alignSelf: "flex-end",
              }}
            />
          </div> */}
          <Box
            sx={{
              position: 'absolute',
              top: 100,
              display: { xs: 'none', md: 'block' }
            }}
          // style={{
          //   position: "absolute",
          //   top: 100,
          // }}
          >
            <AIRAMonoLinesLeft />
          </Box>
        </Paper>
      </Box>
      <TryAiraDialog
        open={openTryAIRADialog}
        handleClose={() => {
          setOpenTryAIRADialog(false);
        }}
      />
    </>
  );
}

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'footer'])),
  },
});

export default Home;
